### ISSUE TITLE
It can't work!

### ISSUE THREAD

**Issue by G4rb3n** [PyAna/PyAna#4]
When I debug at `mu.reg_write(UC_X86_REG_FS, TIB)`,error occur!

**Comment by r0cu3** [comment]
Hi, this project was not maintained by author, and its very basic. You can read about tutorials or other showcases on [Unicorn Engine's Home Page](http://www.unicorn-engine.org). Hope you enjoying.

**Comment by G4rb3n** [comment]
thank you，and I resolve this probem
